# This is a basic workflow to help you get started with Actions

name: 3DPrototype Main CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - 'TestPOC/**'
    branches:
      - betarelease
      - master
  pull_request:
    branches: [ master ]
env:
  packageName: hello-test.sppkg
defaults:
  run:
    working-directory: ./TestPOC
   # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 10.x
        
    - name: Install dependencies     
      run: |
        npm install
                      
    - name: Build solution
      run: gulp build
         
    - name: Test solution
      run: npm test
                   
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
       
    
    - name: Upload Build Package
      uses: actions/upload-artifact@v2
      with:
        name: packageFile
        path: TestPOC/sharepoint/solution/${{ env.packageName }}
      
  deployUAT:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/dev'
    env:
      siteUrl: https://in8sanjc.sharepoint.com/sites/LCEdev

    steps:

    - name: Download pacakge (sppkg file)
      uses: actions/download-artifact@v1
      with:
        name: packageFile
        
    - name: Office 365 CLI Login
      uses: pnp/action-cli-login@v1.0.0
      with:
        ADMIN_USERNAME: ${{ secrets.adminUsername }}
        ADMIN_PASSWORD: ${{ secrets.adminPassword }}
        
    - name: Office 365 CLI Deploy App
      uses: pnp/action-cli-deploy@v1.0.1
      with:
        APP_FILE_PATH: packageFile/${{ env.packageName }}
        SCOPE: sitecollection
        SITE_COLLECTION_URL: ${{ env.siteUrl }}
        OVERWRITE: true  
  deployPROD:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/beta' 
    env:
      siteUrl: https://in8sanjc.sharepoint.com/sites/LCENew

    steps:

    - name: Download pacakge (sppkg file)
      uses: actions/download-artifact@v1
      with:
        name: packageFile

    - name: Office 365 CLI Login
      uses: pnp/action-cli-login@v1.0.0
      with:
        ADMIN_USERNAME: ${{ secrets.adminUsername }}
        ADMIN_PASSWORD: ${{ secrets.adminPassword }}
        
    - name: Office 365 CLI Deploy App
      uses: pnp/action-cli-deploy@v1.0.1
      with:
        APP_FILE_PATH: packageFile/${{ env.packageName }}
        SCOPE: sitecollection
        SITE_COLLECTION_URL: ${{ env.siteUrl }}
        OVERWRITE: true
